// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: gossr/v1/options.proto

package gossrv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageOptions presents options to configure fields to interact with protobuf powered rpc
type MessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// template option configures the name of one or more templates that work together to
	// render the message.
	Template []string `protobuf:"bytes,1,rep,name=template" json:"template,omitempty"`
}

func (x *MessageOptions) Reset() {
	*x = MessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gossr_v1_options_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageOptions) ProtoMessage() {}

func (x *MessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_gossr_v1_options_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageOptions.ProtoReflect.Descriptor instead.
func (*MessageOptions) Descriptor() ([]byte, []int) {
	return file_gossr_v1_options_proto_rawDescGZIP(), []int{0}
}

func (x *MessageOptions) GetTemplate() []string {
	if x != nil {
		return x.Template
	}
	return nil
}

var file_gossr_v1_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*MessageOptions)(nil),
		Field:         1098,
		Name:          "gossr.v1.msg",
		Tag:           "bytes,1098,opt,name=msg",
		Filename:      "gossr/v1/options.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional gossr.v1.MessageOptions msg = 1098;
	E_Msg = &file_gossr_v1_options_proto_extTypes[0]
)

var File_gossr_v1_options_proto protoreflect.FileDescriptor

var file_gossr_v1_options_proto_rawDesc = []byte{
	0x0a, 0x16, 0x67, 0x6f, 0x73, 0x73, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x67, 0x6f, 0x73, 0x73, 0x72, 0x2e,
	0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2c, 0x0a, 0x0e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61,
	0x74, 0x65, 0x3a, 0x4c, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xca, 0x08, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x67, 0x6f, 0x73, 0x73, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x42, 0x9c, 0x01, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x2e, 0x67, 0x6f, 0x73, 0x73, 0x72, 0x2e, 0x76,
	0x31, 0x42, 0x0c, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50,
	0x01, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x72,
	0x65, 0x77, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d,
	0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x73, 0x73, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f,
	0x67, 0x6f, 0x73, 0x73, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x67, 0x6f, 0x73, 0x73, 0x72, 0x76, 0x31,
	0xa2, 0x02, 0x03, 0x47, 0x58, 0x58, 0xaa, 0x02, 0x08, 0x47, 0x6f, 0x73, 0x73, 0x72, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x08, 0x47, 0x6f, 0x73, 0x73, 0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x14, 0x47,
	0x6f, 0x73, 0x73, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x09, 0x47, 0x6f, 0x73, 0x73, 0x72, 0x3a, 0x3a, 0x56, 0x31,
}

var (
	file_gossr_v1_options_proto_rawDescOnce sync.Once
	file_gossr_v1_options_proto_rawDescData = file_gossr_v1_options_proto_rawDesc
)

func file_gossr_v1_options_proto_rawDescGZIP() []byte {
	file_gossr_v1_options_proto_rawDescOnce.Do(func() {
		file_gossr_v1_options_proto_rawDescData = protoimpl.X.CompressGZIP(file_gossr_v1_options_proto_rawDescData)
	})
	return file_gossr_v1_options_proto_rawDescData
}

var file_gossr_v1_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gossr_v1_options_proto_goTypes = []interface{}{
	(*MessageOptions)(nil),              // 0: gossr.v1.MessageOptions
	(*descriptorpb.MessageOptions)(nil), // 1: google.protobuf.MessageOptions
}
var file_gossr_v1_options_proto_depIdxs = []int32{
	1, // 0: gossr.v1.msg:extendee -> google.protobuf.MessageOptions
	0, // 1: gossr.v1.msg:type_name -> gossr.v1.MessageOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gossr_v1_options_proto_init() }
func file_gossr_v1_options_proto_init() {
	if File_gossr_v1_options_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gossr_v1_options_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gossr_v1_options_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_gossr_v1_options_proto_goTypes,
		DependencyIndexes: file_gossr_v1_options_proto_depIdxs,
		MessageInfos:      file_gossr_v1_options_proto_msgTypes,
		ExtensionInfos:    file_gossr_v1_options_proto_extTypes,
	}.Build()
	File_gossr_v1_options_proto = out.File
	file_gossr_v1_options_proto_rawDesc = nil
	file_gossr_v1_options_proto_goTypes = nil
	file_gossr_v1_options_proto_depIdxs = nil
}
