// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: examples/fuzz/v1/test_import.proto

package fuzzv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Enum being imported
type ImportEnum int32

const (
	ImportEnum_IMPORT_ZERO ImportEnum = 0
)

// Enum value maps for ImportEnum.
var (
	ImportEnum_name = map[int32]string{
		0: "IMPORT_ZERO",
	}
	ImportEnum_value = map[string]int32{
		"IMPORT_ZERO": 0,
	}
)

func (x ImportEnum) Enum() *ImportEnum {
	p := new(ImportEnum)
	*p = x
	return p
}

func (x ImportEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImportEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_examples_fuzz_v1_test_import_proto_enumTypes[0].Descriptor()
}

func (ImportEnum) Type() protoreflect.EnumType {
	return &file_examples_fuzz_v1_test_import_proto_enumTypes[0]
}

func (x ImportEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImportEnum.Descriptor instead.
func (ImportEnum) EnumDescriptor() ([]byte, []int) {
	return file_examples_fuzz_v1_test_import_proto_rawDescGZIP(), []int{0}
}

// Message being imported
type ImportMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ImportMessage) Reset() {
	*x = ImportMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_examples_fuzz_v1_test_import_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ImportMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImportMessage) ProtoMessage() {}

func (x *ImportMessage) ProtoReflect() protoreflect.Message {
	mi := &file_examples_fuzz_v1_test_import_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImportMessage.ProtoReflect.Descriptor instead.
func (*ImportMessage) Descriptor() ([]byte, []int) {
	return file_examples_fuzz_v1_test_import_proto_rawDescGZIP(), []int{0}
}

var File_examples_fuzz_v1_test_import_proto protoreflect.FileDescriptor

var file_examples_fuzz_v1_test_import_proto_rawDesc = []byte{
	0x0a, 0x22, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x66, 0x75, 0x7a, 0x7a, 0x2f,
	0x76, 0x31, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x5f, 0x69, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x66,
	0x75, 0x7a, 0x7a, 0x2e, 0x76, 0x31, 0x22, 0x0f, 0x0a, 0x0d, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x1d, 0x0a, 0x0a, 0x49, 0x6d, 0x70, 0x6f, 0x72,
	0x74, 0x45, 0x6e, 0x75, 0x6d, 0x12, 0x0f, 0x0a, 0x0b, 0x49, 0x4d, 0x50, 0x4f, 0x52, 0x54, 0x5f,
	0x5a, 0x45, 0x52, 0x4f, 0x10, 0x00, 0x42, 0xcf, 0x01, 0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x2e, 0x65,
	0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x66, 0x75, 0x7a, 0x7a, 0x2e, 0x76, 0x31, 0x42,
	0x0f, 0x54, 0x65, 0x73, 0x74, 0x49, 0x6d, 0x70, 0x6f, 0x72, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x50, 0x01, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63,
	0x72, 0x65, 0x77, 0x6c, 0x69, 0x6e, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x67, 0x6f, 0x73, 0x73, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2f, 0x66, 0x75, 0x7a, 0x7a, 0x2f, 0x76,
	0x31, 0x3b, 0x66, 0x75, 0x7a, 0x7a, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x45, 0x46, 0x58, 0xaa, 0x02,
	0x10, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x2e, 0x46, 0x75, 0x7a, 0x7a, 0x2e, 0x56,
	0x31, 0xca, 0x02, 0x10, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x5c, 0x46, 0x75, 0x7a,
	0x7a, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1c, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x5c,
	0x46, 0x75, 0x7a, 0x7a, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0xea, 0x02, 0x12, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x73, 0x3a, 0x3a,
	0x46, 0x75, 0x7a, 0x7a, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_examples_fuzz_v1_test_import_proto_rawDescOnce sync.Once
	file_examples_fuzz_v1_test_import_proto_rawDescData = file_examples_fuzz_v1_test_import_proto_rawDesc
)

func file_examples_fuzz_v1_test_import_proto_rawDescGZIP() []byte {
	file_examples_fuzz_v1_test_import_proto_rawDescOnce.Do(func() {
		file_examples_fuzz_v1_test_import_proto_rawDescData = protoimpl.X.CompressGZIP(file_examples_fuzz_v1_test_import_proto_rawDescData)
	})
	return file_examples_fuzz_v1_test_import_proto_rawDescData
}

var file_examples_fuzz_v1_test_import_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_examples_fuzz_v1_test_import_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_examples_fuzz_v1_test_import_proto_goTypes = []interface{}{
	(ImportEnum)(0),       // 0: examples.fuzz.v1.ImportEnum
	(*ImportMessage)(nil), // 1: examples.fuzz.v1.ImportMessage
}
var file_examples_fuzz_v1_test_import_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_examples_fuzz_v1_test_import_proto_init() }
func file_examples_fuzz_v1_test_import_proto_init() {
	if File_examples_fuzz_v1_test_import_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_examples_fuzz_v1_test_import_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ImportMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_examples_fuzz_v1_test_import_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_examples_fuzz_v1_test_import_proto_goTypes,
		DependencyIndexes: file_examples_fuzz_v1_test_import_proto_depIdxs,
		EnumInfos:         file_examples_fuzz_v1_test_import_proto_enumTypes,
		MessageInfos:      file_examples_fuzz_v1_test_import_proto_msgTypes,
	}.Build()
	File_examples_fuzz_v1_test_import_proto = out.File
	file_examples_fuzz_v1_test_import_proto_rawDesc = nil
	file_examples_fuzz_v1_test_import_proto_goTypes = nil
	file_examples_fuzz_v1_test_import_proto_depIdxs = nil
}
